[package]
name = "cookieext"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = "1"
dirs = "4.0"
openssl = "0.10.29"
urlparse = "0.7.3"
rusqlite = "0.26.3"